#!/bin/bash


cp /home/kammo/dotfiles/vim-config/.vimrc  /home/kammo 


if [ -d ~/.vim/bundle/Vundle.vim ]; then 
	
	echo "vundle is install"

	
else

	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

fi

